### ISSUE TITLE
How to verify whether the solution at each stage is correct

### ISSUE THREAD

**Issue by weihaoysgs** [boxuLibrary/drt-vio-init#11]
Thank you for your great work.

I tried to add this initialization scheme to my VIO system. Due to the differences in system design and data structure, I have some engineering implementation details that I would like to sincerely ask you for advice.

Question: How to verify whether the solution at each stage is correct? For example, after solving the LTL constraints, the position (without scale) and rotation of each keyframe are obtained. How to verify the accuracy of the results of this step, because the subsequent alignment will It depends on the result of this step, so you may want to make sure that the solution of this step is correct first.

Looking forward to your reply.

**Comment by boxuLibrary** [comment]
Thank you for your comment. I think you can check the results of each step by running the open-source dataset, e.g. EuRoC, TUM-VI dataset, which contain the groundtruth. The position and translation can be compared in a way as our released code.

**Comment by weihaoysgs** [comment]
OK, thanks for your reply.
