### ISSUE TITLE
When open source VINS-Mono initialization for comparing with drt init

### ISSUE THREAD

**Issue by wuerhan** [boxuLibrary/drt-vio-init#13]
I use same dateset to run VINS-Mono initialization and drt initialization. when I evaluate the total trajectory accuracy, the results reveal tracking accuracy of VINS_MONO is three to five times better than using drt initialization. I see the scale using drt initialization has larger error, but I don't know why.

**Comment by boxuLibrary** [comment]
Hi, thank you for your concern. I think you should check the initialization results for VINS-Mono and our method, such as gravity error, bias error etc. I think this will help you to analysis the results of the total trajectory accuracy.

**Comment by Alex-Beh** [comment]
@wuerhan Would you mind sharing your experiment steps? Could you explain how you achieved it? I am also interested in this topic and am willing to offer help if I can.
