### ISSUE TITLE
补充资料Sec.2

### ISSUE THREAD

**Issue by Demommm** [boxuLibrary/drt-vio-init#14]
您在论文中多次提到详细推导请见补充资料Sec.2，但我在网站上没有找到。
请问在哪里可以找到补充资料Sec.2？
感谢您的回答。

**Comment by boxuLibrary** [comment]
please refer: https://openaccess.thecvf.com/content/CVPR2023/supplemental/He_A_Rotation-Translation-Decoupled_Solution_CVPR_2023_supplemental.pdf
