### ISSUE TITLE
How to transplant drt init into VINS_MONO，replace the original vins initialization? 

### ISSUE THREAD

**Issue by wuerhan** [boxuLibrary/drt-vio-init#15]

**Comment by boilcy** [comment]
check my repo if you still need it.
https://github.com/boilcy/VINS-Mono.git

**Comment by INDEX108** [comment]
> check my repo if you still need it. https://github.com/boilcy/VINS-Mono.git

Hi,I've tried this repo.But there's something wrong with it.
NODES
  /
    feature_tracker (feature_tracker/feature_tracker)
    pose_graph (pose_graph/pose_graph)
    vins_estimator (vins_estimator/vins_estimator)

ROS_MASTER_URI=http://localhost:11311

process[feature_tracker-1]: started with pid [61405]
process[vins_estimator-2]: started with pid [61406]
process[pose_graph-3]: started with pid [61407]
[ INFO] [1715834716.083318903]: init begins
[ INFO] [1715834716.090406815]: Loaded config_file: /home/index108/VINS/DRT_VINS/src/VINS-Mono/feature_tracker/../config/euroc/euroc_config.yaml
result path /home/index108/output//vins_result_no_loop.csv
[ INFO] [1715834716.091029590]: ROW: 480.000000 COL: 752.000000 
[ WARN] [1715834716.091046352]:  fix extrinsic param 
[ INFO] [1715834716.091103482]: Extrinsic_R : 
 0.0148655  -0.999881  0.0041403
  0.999557  0.0149672  0.0257155
-0.0257744 0.00375619   0.999661
[ INFO] [1715834716.091119755]: Extrinsic_T : 
-0.0216401  -0.064677 0.00981073
[ INFO] [1715834716.091131139]: Synchronized sensors, fix time offset: 0
[ INFO] [1715834716.091142733]: INIT: DRT Loosely
[ WARN] [1715834716.091151672]: waiting for image and imu...
vocabulary_file/home/index108/VINS/DRT_VINS/src/VINS-Mono/pose_graph/../support_files/brief_k10L6.bin
loop start load vocabulary
BRIEF_PATTERN_FILE/home/index108/VINS/DRT_VINS/src/VINS-Mono/pose_graph/../support_files/brief_pattern.yml
no previous pose graph
[ WARN] [1715834724.343304612]: gyroscope bias not converge -0.00245898   0.0153236   0.0799477
[ WARN] [1715834724.543914328]: gyroscope bias not converge -0.00159427   0.0169537   0.0830316
[ WARN] [1715834724.735796609]: gyroscope bias not converge -0.00197735   0.0266758    0.083536
[ WARN] [1715834724.947585679]: gyroscope bias not converge -0.00333356   0.0388138   0.0807412
[ WARN] [1715834725.036877546]: gyroscope bias not converge -0.00271899   0.0404334   0.0827656
[ WARN] [1715834725.242807072]: gyroscope bias not converge -0.0032043  0.0344875  0.0805693
[ WARN] [1715834725.437371956]: gyroscope bias not converge -0.00428633   0.0301807    0.077629
[ WARN] [1715834725.551780702]: gyroscope bias not converge -0.00462144   0.0296536   0.0767685
[ WARN] [1715834725.739333941]: gyroscope bias not converge -0.00649432   0.0287829   0.0705355
[ WARN] [1715834725.932372374]: gyroscope bias not converge -0.00660054  0.00589244   0.0695617
[ WARN] [1715834726.035257309]: gyroscope bias not converge -0.0064082 0.00627914    0.07041
[ WARN] [1715834726.240511960]: gyroscope bias not converge -0.00528582   0.0145278   0.0759611
[ WARN] [1715834726.439162558]: gyroscope bias initial calibration -0.00358731    0.011268   0.0821361
[vins_estimator-2] process has died [pid 61406, exit code -11, cmd /home/index108/VINS/DRT_VINS/devel/lib/vins_estimator/vins_estimator __name:=vins_estimator __log:=/home/index108/.ros/log/b5f4be1a-133c-11ef-bf30-6df1c94c400a/vins_estimator-2.log].
log file: /home/index108/.ros/log/b5f4be1a-133c-11ef-bf30-6df1c94c400a/vins_estimator-2*.log

**Comment by boilcy** [comment]
![image](https://github.com/boxuLibrary/drt-vio-init/assets/47935305/b2e32837-482a-4608-b060-57ebff986fdf)
it works on EuRoC MH_01_easy data. It is possible that the initialization error situation was handled incorrectly. could you show me the logfile?

**Comment by INDEX108** [comment]
> ![image](https://private-user-images.githubusercontent.com/47935305/331052884-b2e32837-482a-4608-b060-57ebff986fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDc2NTMsIm5iZiI6MTcxNTg0NzM1MywicGF0aCI6Ii80NzkzNTMwNS8zMzEwNTI4ODQtYjJlMzI4MzctNDgyYS00NjA4LWIwNjAtNTdlYmZmOTg2ZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjN2RiZWM1YTIwMWExZjkxMzk1NDhiNWExOWJjOWFjNjAyNWFiNWZjYTllYjQzNTdkYzYzMWRhMjY2ZTMxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rmmQYUqRwRaZw6Q8xJ5V1vxpTTVPxgz6Awhy9SGRLDg) it works on EuRoC MH_01_easy data. It is possible that the initialization error situation was handled incorrectly. could you show me the logfile?

Thank you very much, I have resolved it. By the way, is the accuracy of this repo higher than Vinsmono? How did you evaluate the initialization effect of the DRT method?

**Comment by boilcy** [comment]
EuRoc dataset has Ground-Truth.
.../datasets/EuRoC/MH_03_medium/mav0/state_groundtruth_estimate0 if it's in folder format,
topic /leica/position    3099 msgs    : geometry_msgs/PointStamped if it's rosbag format.
I haven't evaluated it yet.

**Comment by Yingsheng123** [comment]
hello，the Initialization effect is not well ，do you know the reason

**Comment by Yingsheng123** [comment]
> EuRoc dataset has Ground-Truth. .../datasets/EuRoC/MH_03_medium/mav0/state_groundtruth_estimate0 if it's in folder format, topic /leica/position 3099 msgs : geometry_msgs/PointStamped if it's rosbag format. I haven't evaluated it yet.

have you evaluated it?

**Comment by jerryjifjsdbf** [comment]
> EuRoc dataset has Ground-Truth. .../datasets/EuRoC/MH_03_medium/mav0/state_groundtruth_estimate0 if it's in folder format, topic /leica/position 3099 msgs : geometry_msgs/PointStamped if it's rosbag format. I haven't evaluated it yet.

请问你已经把这个方法集成到vins-mono中吗，定位精度的效果咋样

**Comment by Yingsheng123** [comment]
> > EuRoc dataset has Ground-Truth. .../datasets/EuRoC/MH_03_medium/mav0/state_groundtruth_estimate0 if it's in folder format, topic /leica/position 3099 msgs : geometry_msgs/PointStamped if it's rosbag format. I haven't evaluated it yet.
> 
> 请问你已经把这个方法集成到vins-mono中吗，定位精度的效果咋样

我使用重力计算方法和vins-mono一样，其余部分使用了这个方法，效果不是很好。发现ros中初始化部分的效果不如直接运行这个源码，我也不太清楚问题在哪里

**Comment by jerryjifjsdbf** [comment]
> > > EuRoc dataset has Ground-Truth. .../datasets/EuRoC/MH_03_medium/mav0/state_groundtruth_estimate0 if it's in folder format, topic /leica/position 3099 msgs : geometry_msgs/PointStamped if it's rosbag format. I haven't evaluated it yet.
> > 
> > 
> > 请问你已经把这个方法集成到vins-mono中吗，定位精度的效果咋样
> 
> 我使用重力计算方法和vins-mono一样，其余部分使用了这个方法，效果不是很好。发现ros中初始化部分的效果不如直接运行这个源码，我也不太清楚问题在哪里
请问你现在解决了吗

**Comment by Yingsheng123** [comment]
> > > > EuRoc dataset has Ground-Truth. .../datasets/EuRoC/MH_03_medium/mav0/state_groundtruth_estimate0 if it's in folder format, topic /leica/position 3099 msgs : geometry_msgs/PointStamped if it's rosbag format. I haven't evaluated it yet.
> > > 
> > > 
> > > 请问你已经把这个方法集成到vins-mono中吗，定位精度的效果咋样
> > 
> > 
> > 我使用重力计算方法和vins-mono一样，其余部分使用了这个方法，效果不是很好。发现ros中初始化部分的效果不如直接运行这个源码，我也不太清楚问题在哪里
> > 请问你现在解决了吗

还没有，不过通过实验发现，这个方法和smf在存储要使用特征点有些许差别，需要制定一些策略
