### ISSUE TITLE
Is it necessary to calculate the Jacobian when performing gyro bias tight coupling optimization?

### ISSUE THREAD

**Issue by weihaoysgs** [boxuLibrary/drt-vio-init#9]
Great work. If I understand correctly, regarding the gyro zero bias tight coupling optimization part, although there is also a calculation part about Jacobian in the program, the calculation uses ceres automatic derivation. I would like to ask if this part Can be commented out.

**Comment by boxuLibrary** [comment]
Thank you for your comment. In our released code, we optimize the residual of the rotation related constraints with ceres automatic derivation. The jacobian is not used.  However, in the original opengv code, the author regards the Jacobian as the residual and optimized it. In the experiments, the latter is unstable.

**Comment by weihaoysgs** [comment]
OK, thank you for your reply, Looking forward to your future excellent work.
